# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'Paragrafo',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('rodada', models.IntegerField()),
                ('atendida', models.BooleanField()),
            ],
            options={
                'db_table': 'Solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateTimeField()),
                ('moderador_participa', models.BooleanField()),
                ('titulo', models.TextField(max_length=200)),
                ('primeiro_paragrafo', models.TextField(max_length=1000)),
                ('tempo_participante', models.IntegerField()),
                ('numero_rodadas', models.IntegerField()),
                ('encerrado', models.BooleanField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Genero')),
            ],
            options={
                'db_table': 'Texto',
            },
        ),
        migrations.CreateModel(
            name='Texto_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('cancelado', models.BooleanField()),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Texto')),
            ],
            options={
                'db_table': 'Texto_Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='texto_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Usuario'),
        ),
        migrations.AddField(
            model_name='texto',
            name='moderador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Usuario'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Texto'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Usuario'),
        ),
        migrations.AddField(
            model_name='paragrafo',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Texto'),
        ),
        migrations.AddField(
            model_name='paragrafo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Usuario'),
        ),
    ]
