# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
        migrations.RenameModel(
            old_name='Paragrafo',
            new_name='Paragrafos',
        ),
        migrations.RenameModel(
            old_name='Solicitacao',
            new_name='Solicitacaos',
        ),
        migrations.RenameModel(
            old_name='Texto_Usuario',
            new_name='Texto_Usuarios',
        ),
        migrations.RenameModel(
            old_name='Texto',
            new_name='Textos',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.AlterModelTable(
            name='generos',
            table='Generos',
        ),
        migrations.AlterModelTable(
            name='paragrafos',
            table='Paragrafos',
        ),
        migrations.AlterModelTable(
            name='solicitacaos',
            table='Solicitacaos',
        ),
        migrations.AlterModelTable(
            name='texto_usuarios',
            table='Texto_Usuarios',
        ),
        migrations.AlterModelTable(
            name='textos',
            table='Textos',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
