# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20160623_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Paragrafos',
            new_name='Paragrafo',
        ),
        migrations.RenameModel(
            old_name='Solicitacaos',
            new_name='Solicitacao',
        ),
        migrations.RenameModel(
            old_name='Textos',
            new_name='Texto',
        ),
        migrations.RenameModel(
            old_name='Texto_Usuarios',
            new_name='Texto_Usuario',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='Genero',
        ),
        migrations.AlterModelTable(
            name='paragrafo',
            table='Paragrafo',
        ),
        migrations.AlterModelTable(
            name='solicitacao',
            table='Solicitacao',
        ),
        migrations.AlterModelTable(
            name='texto',
            table='Texto',
        ),
        migrations.AlterModelTable(
            name='texto_usuario',
            table='Texto_Usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
