# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160623_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Tipo_Solicitacao'),
        ),
    ]
