# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20160624_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cod_usuario',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
