# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_usuario_cod_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cod_usuario',
        ),
    ]
