# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_remove_usuario_cod_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='rodada_atual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paragrafo',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paragrafo',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('V', 'Passar a vez'), ('P', 'Pular rodada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='texto',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Genero'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='numero_rodadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='primeiro_paragrafo',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='tempo_participante',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='titulo',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tipo_Solicitacao',
        ),
    ]
