# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20160628_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='numero_linhas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Genero'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='numero_rodadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='primeiro_paragrafo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='rodada_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='tempo_participante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='texto',
            name='titulo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
