# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20160721_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='ordem_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
