# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_texto_ordem_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='rodada_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
