# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20160731_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragrafo',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paragrafo',
            name='rodada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
